### ISSUE TITLE
Encoding Issues with Python

### ISSUE THREAD

**Issue by benboeck** [h3xstream/http-script-generator#18]
Python scripts produced by the Burp extension erroneously percent-encode the payload.
This is due to _requests_ automatic percent encoding.
One solution would be to use a string as described here: http://stackoverflow.com/questions/23496750/how-to-prevent-python-requests-from-percent-encoding-my-urls

``` python
payload = {'format': 'json', 'key': 'site:dummy+type:example+group:wheel'}
payload_str = "&".join("%s=%s" % (k,v) for k,v in payload.items())
# 'format=json&key=site:dummy+type:example+group:wheel'
r = requests.get(url, params=payload_str)
```

**Comment by h3xstream** [comment]
Currently the parameters are [blindly URL decoded](https://github.com/h3xstream/http-script-generator/blob/master/scriptgen-burp-plugin/src/main/java/burp/BurpHttpRequestMapper.java#L63) because their is an assumption that library will encode the parameter later.

The main objective of the plugin is to repeat the exact same thing. Their is also a goal to make the queries readable and the scripts slightly elegant (not socket level api).

Looking at the behavior you mention, I would propose this:

 - If a special character is not encoded in the URL or body parameter, the script generated would look like the sample you gave.
 - If no "unencoded" characters are found, then the existing syntax will be use.

I'm curious what trigger the "unencoded" request you mention. Is it a desktop browser, a mobile browser or a specific library ?

## Specific testing required

I know Chrome doesn't always encode URL parameter. I need to make sure that it doesn't start using the raw method most of the time.

**Comment by wr3ck5** [comment]
Here is a snippet that your extension produced:    card%5Blitle
When I printed what python sent as the request it was: card%255Blitle
So what appears to going on is that the browser encodes the '[' and your program leaves the encoded output in the script then python request encodes it again which turns the % into the encoded %25

This was using Firefox and in a POST parameter.

Good luck.

**Comment by h3xstream** [comment]
@wr3ck5 Can you give a complete HTTP request against http://httpbin.org/

```
POST / HTTP/1.1
Host: httpbin.org

EXAMPLE_HERE
```

**Comment by wr3ck5** [comment]
It looks fine on httpbin so something else must be triggering it.
I thought it was just maybe the bracket but...

POST / HTTP/1.1
Host: httpbin.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Cookie: _ga=GA1.2.1656864815.1461362014; _gat=1
Connection: close
Cache-Control: max-age=0
Content-Length: 12

fred[blah]=5

Your generator produces this script for that parameter: paramsPost = {"fred[blah]":"5"}


The URL I was working on was for a client so I can't just paste it. Suffice it to say that in the very long post data I had to replace all the %5b and %5d with [] in the code produced.

Still, much better than writing the code myself.

**Comment by h3xstream** [comment]
This build should include a fix.

[scriptgen-burp-plugin-5.jar.zip](https://github.com/h3xstream/http-script-generator/files/646685/scriptgen-burp-plugin-5.jar.zip)

# What was change

Using systematically raw body did seems right, The idea of the plugin is to have readable script after all.
There will be a fall back to unencoded string only when special characters that could be encoded by requests are present.
At the moment, those special characers are `[` and `]`.
